config/routes.rb
Rails.application.routes.draw do
  resources :timesheets

  resources :oil_exchanges

  resources :refuels

  resources :expenses

  get 'expenses/import-gnucash' => 'expense#import_gnucash'

end

app/models/oil_exchange.rb
class OilExchange < ActiveRecord::Base
end

app/controllers/oil_exchanges_controller.rb
class OilExchangesController < ApplicationController
  before_action :set_oil_exchange, only: [:show, :edit, :update, :destroy]

  # GET /oil_exchanges
  # GET /oil_exchanges.json
  def index
    @oil_exchanges = OilExchange.all
  end

  # GET /oil_exchanges/1
  # GET /oil_exchanges/1.json
  def show
  end

  # GET /oil_exchanges/new
  def new
    @oil_exchange = OilExchange.new
  end

  # GET /oil_exchanges/1/edit
  def edit
  end

  # POST /oil_exchanges
  # POST /oil_exchanges.json
  def create
    @oil_exchange = OilExchange.new(oil_exchange_params)

    respond_to do |format|
      if @oil_exchange.save
        format.html { redirect_to @oil_exchange, notice: 'Oil exchange was successfully created.' }
        format.json { render :show, status: :created, location: @oil_exchange }
      else
        format.html { render :new }
        format.json { render json: @oil_exchange.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /oil_exchanges/1
  # PATCH/PUT /oil_exchanges/1.json
  def update
    respond_to do |format|
      if @oil_exchange.update(oil_exchange_params)
        format.html { redirect_to @oil_exchange, notice: 'Oil exchange was successfully updated.' }
        format.json { render :show, status: :ok, location: @oil_exchange }
      else
        format.html { render :edit }
        format.json { render json: @oil_exchange.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /oil_exchanges/1
  # DELETE /oil_exchanges/1.json
  def destroy
    @oil_exchange.destroy
    respond_to do |format|
      format.html { redirect_to oil_exchanges_url, notice: 'Oil exchange was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_oil_exchange
      @oil_exchange = OilExchange.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def oil_exchange_params
      params.require(:oil_exchange).permit(:date, :KM, :amount, :price, :observation)
    end
end

app/helpers/oil_exchanges_helper.rb
module OilExchangesHelper
end

app/views/oil_exchanges/_form.html.erb
<%= form_for(@oil_exchange) do |f| %>
  <% if @oil_exchange.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@oil_exchange.errors.count, "error") %> prohibited this oil_exchange from being saved:</h2>

      <ul>
      <% @oil_exchange.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :KM %><br>
    <%= f.text_field :KM %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :observation %><br>
    <%= f.text_field :observation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/oil_exchanges/edit.html.erb
<h1>Editing oil_exchange</h1>

<%= render 'form' %>

<%= link_to 'Show', @oil_exchange %> |
<%= link_to 'Back', oil_exchanges_path %>

app/views/oil_exchanges/index.html.erb
<h1>Listing oil_exchanges</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Km</th>
      <th>Amount</th>
      <th>Price</th>
      <th>Observation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @oil_exchanges.each do |oil_exchange| %>
      <tr>
        <td><%= oil_exchange.date %></td>
        <td><%= oil_exchange.KM %></td>
        <td><%= oil_exchange.amount %></td>
        <td><%= oil_exchange.price %></td>
        <td><%= oil_exchange.observation %></td>
        <td><%= link_to 'Show', oil_exchange %></td>
        <td><%= link_to 'Edit', edit_oil_exchange_path(oil_exchange) %></td>
        <td><%= link_to 'Destroy', oil_exchange, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Oil exchange', new_oil_exchange_path %>

app/views/oil_exchanges/new.html.erb
<h1>New oil_exchange</h1>

<%= render 'form' %>

<%= link_to 'Back', oil_exchanges_path %>

app/views/oil_exchanges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @oil_exchange.date %>
</p>

<p>
  <strong>Km:</strong>
  <%= @oil_exchange.KM %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @oil_exchange.amount %>
</p>

<p>
  <strong>Price:</strong>
  <%= @oil_exchange.price %>
</p>

<p>
  <strong>Observation:</strong>
  <%= @oil_exchange.observation %>
</p>

<%= link_to 'Edit', edit_oil_exchange_path(@oil_exchange) %> |
<%= link_to 'Back', oil_exchanges_path %>