config/routes.rb
Rails.application.routes.draw do
  resources :timesheets

  resources :oil_exchanges

  resources :refuels

  resources :expenses

  get 'expenses/import-gnucash' => 'expense#import_gnucash'

end

app/models/timesheet.rb
class Timesheet < ActiveRecord::Base
end

app/controllers/timesheets_controller.rb
class TimesheetsController < ApplicationController
  before_action :set_timesheet, only: [:show, :edit, :update, :destroy]

  # GET /timesheets
  # GET /timesheets.json
  def index
    @timesheets = Timesheet.all
  end

  # GET /timesheets/1
  # GET /timesheets/1.json
  def show
  end

  # GET /timesheets/new
  def new
    @timesheet = Timesheet.new
  end

  # GET /timesheets/1/edit
  def edit
  end

  # POST /timesheets
  # POST /timesheets.json
  def create
    @timesheet = Timesheet.new(timesheet_params)

    respond_to do |format|
      if @timesheet.save
        format.html { redirect_to @timesheet, notice: 'Timesheet was successfully created.' }
        format.json { render :show, status: :created, location: @timesheet }
      else
        format.html { render :new }
        format.json { render json: @timesheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /timesheets/1
  # PATCH/PUT /timesheets/1.json
  def update
    respond_to do |format|
      if @timesheet.update(timesheet_params)
        format.html { redirect_to @timesheet, notice: 'Timesheet was successfully updated.' }
        format.json { render :show, status: :ok, location: @timesheet }
      else
        format.html { render :edit }
        format.json { render json: @timesheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timesheets/1
  # DELETE /timesheets/1.json
  def destroy
    @timesheet.destroy
    respond_to do |format|
      format.html { redirect_to timesheets_url, notice: 'Timesheet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timesheet
      @timesheet = Timesheet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def timesheet_params
      params.require(:timesheet).permit(:date, :leaving_early, :official_shift, :checkin, :checkin_machine, :checkin_motive, :checkout, :checkout_machine, :checkout_motive)
    end
end

app/helpers/timesheets_helper.rb
module TimesheetsHelper
end

app/views/timesheets/_form.html.erb
<%= form_for(@timesheet) do |f| %>
  <% if @timesheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@timesheet.errors.count, "error") %> prohibited this timesheet from being saved:</h2>

      <ul>
      <% @timesheet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :leaving_early %><br>
    <%= f.time_select :leaving_early %>
  </div>
  <div class="field">
    <%= f.label :official_shift %><br>
    <%= f.check_box :official_shift %>
  </div>
  <div class="field">
    <%= f.label :checkin %><br>
    <%= f.time_select :checkin %>
  </div>
  <div class="field">
    <%= f.label :checkin_machine %><br>
    <%= f.text_field :checkin_machine %>
  </div>
  <div class="field">
    <%= f.label :checkin_motive %><br>
    <%= f.text_field :checkin_motive %>
  </div>
  <div class="field">
    <%= f.label :checkout %><br>
    <%= f.time_select :checkout %>
  </div>
  <div class="field">
    <%= f.label :checkout_machine %><br>
    <%= f.text_field :checkout_machine %>
  </div>
  <div class="field">
    <%= f.label :checkout_motive %><br>
    <%= f.text_field :checkout_motive %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/timesheets/edit.html.erb
<h1>Editing timesheet</h1>

<%= render 'form' %>

<%= link_to 'Show', @timesheet %> |
<%= link_to 'Back', timesheets_path %>

app/views/timesheets/index.html.erb
<h1>Listing timesheets</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Leaving early</th>
      <th>Official shift</th>
      <th>Checkin</th>
      <th>Checkin machine</th>
      <th>Checkin motive</th>
      <th>Checkout</th>
      <th>Checkout machine</th>
      <th>Checkout motive</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @timesheets.each do |timesheet| %>
      <tr>
        <td><%= timesheet.date %></td>
        <td><%= timesheet.leaving_early %></td>
        <td><%= timesheet.official_shift %></td>
        <td><%= timesheet.checkin %></td>
        <td><%= timesheet.checkin_machine %></td>
        <td><%= timesheet.checkin_motive %></td>
        <td><%= timesheet.checkout %></td>
        <td><%= timesheet.checkout_machine %></td>
        <td><%= timesheet.checkout_motive %></td>
        <td><%= link_to 'Show', timesheet %></td>
        <td><%= link_to 'Edit', edit_timesheet_path(timesheet) %></td>
        <td><%= link_to 'Destroy', timesheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Timesheet', new_timesheet_path %>

app/views/timesheets/new.html.erb
<h1>New timesheet</h1>

<%= render 'form' %>

<%= link_to 'Back', timesheets_path %>

app/views/timesheets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @timesheet.date %>
</p>

<p>
  <strong>Leaving early:</strong>
  <%= @timesheet.leaving_early %>
</p>

<p>
  <strong>Official shift:</strong>
  <%= @timesheet.official_shift %>
</p>

<p>
  <strong>Checkin:</strong>
  <%= @timesheet.checkin %>
</p>

<p>
  <strong>Checkin machine:</strong>
  <%= @timesheet.checkin_machine %>
</p>

<p>
  <strong>Checkin motive:</strong>
  <%= @timesheet.checkin_motive %>
</p>

<p>
  <strong>Checkout:</strong>
  <%= @timesheet.checkout %>
</p>

<p>
  <strong>Checkout machine:</strong>
  <%= @timesheet.checkout_machine %>
</p>

<p>
  <strong>Checkout motive:</strong>
  <%= @timesheet.checkout_motive %>
</p>

<%= link_to 'Edit', edit_timesheet_path(@timesheet) %> |
<%= link_to 'Back', timesheets_path %>