config/routes.rb
Rails.application.routes.draw do
  resources :timesheets

  resources :oil_exchanges

  resources :refuels

  resources :expenses

  get 'expenses/import-gnucash' => 'expense#import_gnucash'

end

app/models/refuel.rb
class Refuel < ActiveRecord::Base
end

app/controllers/refuels_controller.rb
class RefuelsController < ApplicationController
  before_action :set_refuel, only: [:show, :edit, :update, :destroy]

  # GET /refuels
  # GET /refuels.json
  def index
    @refuels = Refuel.all
  end

  # GET /refuels/1
  # GET /refuels/1.json
  def show
  end

  # GET /refuels/new
  def new
    @refuel = Refuel.new
  end

  # GET /refuels/1/edit
  def edit
  end

  # POST /refuels
  # POST /refuels.json
  def create
    @refuel = Refuel.new(refuel_params)

    respond_to do |format|
      if @refuel.save
        format.html { redirect_to @refuel, notice: 'Refuel was successfully created.' }
        format.json { render :show, status: :created, location: @refuel }
      else
        format.html { render :new }
        format.json { render json: @refuel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /refuels/1
  # PATCH/PUT /refuels/1.json
  def update
    respond_to do |format|
      if @refuel.update(refuel_params)
        format.html { redirect_to @refuel, notice: 'Refuel was successfully updated.' }
        format.json { render :show, status: :ok, location: @refuel }
      else
        format.html { render :edit }
        format.json { render json: @refuel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /refuels/1
  # DELETE /refuels/1.json
  def destroy
    @refuel.destroy
    respond_to do |format|
      format.html { redirect_to refuels_url, notice: 'Refuel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_refuel
      @refuel = Refuel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def refuel_params
      params.require(:refuel).permit(:date, :KM, :amount, :price, :gas_station, :observation)
    end
end

app/helpers/refuels_helper.rb
module RefuelsHelper
end

app/views/refuels/_form.html.erb
<%= form_for(@refuel) do |f| %>
  <% if @refuel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@refuel.errors.count, "error") %> prohibited this refuel from being saved:</h2>

      <ul>
      <% @refuel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :KM %><br>
    <%= f.text_field :KM %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :gas_station %><br>
    <%= f.text_field :gas_station %>
  </div>
  <div class="field">
    <%= f.label :observation %><br>
    <%= f.text_field :observation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/refuels/edit.html.erb
<h1>Editing refuel</h1>

<%= render 'form' %>

<%= link_to 'Show', @refuel %> |
<%= link_to 'Back', refuels_path %>

app/views/refuels/index.html.erb
<h1>Listing refuels</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Km</th>
      <th>Amount</th>
      <th>Price</th>
      <th>Gas station</th>
      <th>Observation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @refuels.each do |refuel| %>
      <tr>
        <td><%= refuel.date %></td>
        <td><%= refuel.KM %></td>
        <td><%= refuel.amount %></td>
        <td><%= refuel.price %></td>
        <td><%= refuel.gas_station %></td>
        <td><%= refuel.observation %></td>
        <td><%= link_to 'Show', refuel %></td>
        <td><%= link_to 'Edit', edit_refuel_path(refuel) %></td>
        <td><%= link_to 'Destroy', refuel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Refuel', new_refuel_path %>

app/views/refuels/new.html.erb
<h1>New refuel</h1>

<%= render 'form' %>

<%= link_to 'Back', refuels_path %>

app/views/refuels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @refuel.date %>
</p>

<p>
  <strong>Km:</strong>
  <%= @refuel.KM %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @refuel.amount %>
</p>

<p>
  <strong>Price:</strong>
  <%= @refuel.price %>
</p>

<p>
  <strong>Gas station:</strong>
  <%= @refuel.gas_station %>
</p>

<p>
  <strong>Observation:</strong>
  <%= @refuel.observation %>
</p>

<%= link_to 'Edit', edit_refuel_path(@refuel) %> |
<%= link_to 'Back', refuels_path %>