config/routes.rb
Rails.application.routes.draw do
  resources :timesheets

  resources :oil_exchanges

  resources :refuels

  resources :expenses

  get 'expenses/import-gnucash' => 'expense#import_gnucash'

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = Expense.all
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Import data into gnucash program using the python's bind
  def import_gnucash

    importer = "/home/jefferson/universal/projects/gnucash-qif-import/import.py"
    gnucash_file = "/home/jefferson/universal/documents/financial/gnucash/personal_gnucash.gnucash"
    # TODO export from sqlite to qif file format to import into gnucash data file
    qif_file = ""
    python_cmd = Escape.shell_command(['python', importer, "-v", "-f", gnucash_file, qif_file]).to_s
    system python_cmd
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:date, :amount, :accountFrom, :accountTo, :memo)
    end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_form.html.erb
<%= form_for(@expense) do |f| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% @expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :accountFrom %><br>
    <%= f.text_field :accountFrom %>
  </div>
  <div class="field">
    <%= f.label :accountTo %><br>
    <%= f.text_field :accountTo %>
  </div>
  <div class="field">
    <%= f.label :memo %><br>
    <%= f.text_field :memo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render 'form' %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<h1>Listing expenses</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Amount</th>
      <th>Accountfrom</th>
      <th>Accountto</th>
      <th>Memo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
        <td><%= expense.date %></td>
        <td><%= expense.amount %></td>
        <td><%= expense.accountFrom %></td>
        <td><%= expense.accountTo %></td>
        <td><%= expense.memo %></td>
        <td><%= link_to 'Show', expense %></td>
        <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
        <td><%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expense', new_expense_path %>

app/views/expenses/new.html.erb
<h1>New expense</h1>

<%= render 'form' %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @expense.date %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @expense.amount %>
</p>

<p>
  <strong>Accountfrom:</strong>
  <%= @expense.accountFrom %>
</p>

<p>
  <strong>Accountto:</strong>
  <%= @expense.accountTo %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @expense.memo %>
</p>

<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>